name: Tests

on:
  push:
    branches-ignore:
      - master

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - name: Prepare branch on runner
      uses: actions/checkout@v3
    - name: Build & Test
      run: xcodebuild build clean test -scheme "Uptech iOS Helpers" -destination "platform=iOS Simulator,name=IPhone 11"
